import Navbar from "./components/Navbar";
import "./globals.css";
import RotatingText from "./components/RotatingText";
import SplashCursor from "./components/SplashCursor";

import SessionWrapper from "./components/SessionWrapper";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className="min-h-screen  relative h-full w-full bg-black">
        <SessionWrapper>
          {/* <SplashCursor/> */}
          <div className="absolute -z-1 bottom-0 left-0 right-0 top-0 bg-[linear-gradient(to_right,#4f4f4f2e_1px,transparent_1px),linear-gradient(to_bottom,#8080800a_1px,transparent_1px)] bg-[size:14px_24px]"></div>
          <div className="absolute -z-10 left-[30px] right-0 top-[-30%] h-[1000px] w-[1000px] rounded-full bg-[radial-gradient(circle_500px_at_50%_300px,#fbfbfb36,#000)]"></div>
          {children}
          <footer className="fixed bottom-0 text-center text-gray-500 text-sm p-4 w-full">
            © {new Date().getFullYear()} Logistics. All rights reserved.
          </footer>
        </SessionWrapper>
      </body>
    </html>
  );
}
